homework9: main.o pokemon.o gyarados.o heracross.o typhlosion.o
	g++ -o homework9 main.o pokemon.o gyarados.o heracross.o typhlosion.o

main.o: main.cpp
	g++ -ansi -pedantic-errors -Wall -c main.cpp

gyarados.o: gyarados.cpp gyarados.h
	g++ -ansi -pedantic-errors -Wall -c gyarados.cpp

heracross.o: heracross.cpp heracross.h
	g++ -ansi -pedantic-errors -Wall -c heracross.cpp

typhlosion.o: typhlosion.cpp typhlosion.h
	g++ -ansi -pedantic-errors -Wall -c typhlosion.cpp

pokemon.o: pokemon.cpp pokemon.h
	g++ -ansi -pedantic-errors -Wall -c pokemon.cpp
